/**
 * Whether there are credits left to generate anything with.
 *
 * A switch rather than a check against a balance, because there is no balance
 * to read: the credits are on an account with a provider, and the honest
 * signal that they have run out is a person deciding they have. Flip it back
 * when they are topped up.
 *
 * Same shape as `OPEN_FOR_BUSINESS` in lib/plans.ts, and for the same reason —
 * a deployment can disagree via the environment, but the code carries the
 * decision so the app is never accidentally selling something it cannot do.
 *
 * `NEXT_PUBLIC_` because the composer and the badge are client components and
 * this decides what they draw. It says nothing secret; anyone can see it by
 * pressing Enter.
 */
const CREDITS_SPENT = true

export const GENERATION_PAUSED =
  CREDITS_SPENT && process.env.NEXT_PUBLIC_GENERATION_PAUSED !== 'false'

/**
 * What to say about it.
 *
 * Kept beside the switch so the badge, the dialog and anything added later
 * cannot drift into telling three different stories about the same outage.
 */
export const PAUSED_BADGE = 'Out of AI credits'

export const PAUSED_TITLE = 'We have run out of AI credits'

export const PAUSED_BODY =
  'More people turned up than we had credits for, so new maps and lessons are paused for a moment. Nothing you have made has gone anywhere.'

export const PAUSED_POINTER =
  'The lessons in the sidebar were generated by other people and are there as demos — have a watch of those in the meantime.'
